import { Schema, model } from 'mongoose';

/**
 * NoteChunk Schema
 * Represents a chunked segment of a note document, ready for embedding and RAG retrieval.
 * 
 * FR-11: Notes shall be chunked/embedded to power a scoped AI Q&A assistant.
 * 
 * Chunking strategy (implemented in Day 7, embeddings generated Day 9):
 * - Split uploaded notes into logical segments by page or semantic boundary
 * - Each chunk is stored separately with its source note/tutor context
 * - On Day 9: chunks are embedded via Gemini, enabling cosine similarity search
 * - On Day 10: student questions are embedded and matched against chunk embeddings
 * 
 * Day 7 scope: Schema and chunking logic only (no embedding generation yet).
 * Day 9 scope: Embedding generation via Gemini API (handled in services/ragService.js).
 */
const NoteChunkSchema = new Schema(
  {
    noteId: { type: Schema.Types.ObjectId, ref: 'Note', required: true },
    tutorId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    
    // Text content of this chunk
    text: { 
      type: String, 
      required: true,
      minlength: [1, 'Chunk text cannot be empty'],
      maxlength: [5000, 'Chunk text cannot exceed 5000 characters']
    },
    
    // Page number where this chunk appears (1-indexed)
    // Used to link back to preview pages and source material
    pageNumber: { 
      type: Number, 
      required: true,
      min: [1, 'Page number must be >= 1']
    },
    
    // Embedding vector generated by Gemini API (Day 9)
    // Array of 768-dimensional embeddings (Google Gemini text-embedding-004)
    // Null until Day 9 when embeddings are generated
    embedding: {
      type: [Number],
      default: null,
      validate: {
        validator: (v) => v === null || (Array.isArray(v) && v.length === 768),
        message: 'Embedding must be null or a 768-dimensional vector'
      }
    },
    
    // Metadata for debugging and audit
    chunkIndex: { 
      type: Number, 
      required: true 
    }, // Order within the note (0-indexed)
    charCount: { 
      type: Number, 
      required: true 
    }, // Number of characters in this chunk
  },
  { timestamps: true }
);

// Index for efficient RAG retrieval:
// - Query by noteId (all chunks for a note)
// - Query by tutorId (all chunks from a tutor, for scoped search)
// - Find chunks by embedding similarity (Day 9+)
NoteChunkSchema.index({ noteId: 1 });
NoteChunkSchema.index({ tutorId: 1 });
NoteChunkSchema.index({ noteId: 1, pageNumber: 1 });

export default model('NoteChunk', NoteChunkSchema);
